requires 'DateTime::Format::ISO8601';
requires 'Digest::SHA1;
requires 'Fuse';
requires 'Moose';
requires 'Net::Amazon::S3';
requires 'Path::Class';
requires 'methods';
requires 'invoker';
requires 'YAML';
